### ISSUE TITLE
Interferences with checkstyle plugin?

### ISSUE THREAD

**Issue by karussell** [hbakkum/resolve-parent-version-maven-plugin#1]
I really like that you already solved the problem [we are facing](https://github.com/graphhopper/graphhopper/issues/1288) :) - thanks a lot!

We migrated to this new release style (see commit [here](https://github.com/graphhopper/graphhopper/commit/3b34d73abee3567b38ccd36054fca5b43faa5131) but when we add [your plugin here](https://github.com/graphhopper/graphhopper/commit/f6a64ed3c02c11bd23532b36a9f49f44e9b4650a) the checkstyle plugin has a problem to find its config (which is also an xml):

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (default-cli) 
on project graphhopper-parent: 
Failed during checkstyle execution: Unable to find configuration file at location: 
checkstyle.xml: Could not find resource 'checkstyle.xml'. -> [Help 1]
```

You can reproduce this with:
```
mvn clean test verify checkstyle:check
```
When I look at your code this error does not make any sense but when I exclude your plugin again it builds fine.

**Comment by karussell** [comment]
It is somehow the combination of test and checkstyle:check. If I run them separately, it works. Also your plugin seems to touch really just the pom.xml. Strange.

**Comment by hbakkum** [comment]
Hi there,

No worries - thanks for using the plugin.

I've taken a look at whats going on in the checkstyle source code. It seems to load the checkstyle config file relative to the modules pom file. This is fine if the pom file is in the same directory as the modules basedir, but my plugin outputs the modules pom file (with properties resolved in the version element) into the target directory. IMO the checkstyle plugin should be loading the config file relative to the modules basedir (which never changes) rather than (or in addition to) the pom file dir. I'll raise an issue (I'll update this thread with a link once done) against the checkstyle plugin and see what they say.

In the meantime, there are probably two reasonable workarounds.

First would be to prefix your checkstyle.xml path with the ${user.dir} property (which resolves to the dir the maven executable is being run from), e.g.

`<configLocation>${user.dir}/core/files/checkstyle.xml</configLocation>`  

This does have the rather annoying downside that you can only run maven from your projects parent pom directory, i.e. you could not run a maven build from a submodule as the checkstyle.xml path would then be wrong.

The other option would be to set a property in every pom file, ${root.dir}, that points to your parent poms basedir. 
For example, in your parent pom you would have:
`<root.dir>${project.basedir}</root.dir>`

And each of your submodules would have:
`<root.dir>${project.parent.basedir}</root.dir>`

And finally your checkstyle config location would be:
`<configLocation>${root.dir}/core/files/checkstyle.xml</configLocation>`

Hopefully one of those workarounds is acceptable. I'll need to think on this some more to see if there are any better solutions. Although I suspect without a change to the checkstyle plugin loading config relative to the basedir rather than pom dir we may be left with only these options.

Cheers,
Hayden

**Comment by karussell** [comment]
Thanks a lot for your time, explanation and investigation!

> downside that you can only run maven from your projects parent pom directory

This is not a problem at the moment, so I'll try this.

**Comment by karussell** [comment]
Nice, works and fixes another problem I had with the previous workaround :) - thanks again!
